spring:
  application:
    name: api-gateway-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: test
      port: 27017
      host: localhost


server:
  port: 8080

zuul:
  prefix: /api
  routes:
    product-service:
      path: /product/*
      serviceId: product-service
      url: http://localhost:8081/product
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
